name: flutter_alarm_app
description: App de alarmas con Firebase y notificaciones locales
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versiones estables y entre sí compatibles)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6

  # Estado
  flutter_riverpod: ^2.4.9

  # Notificaciones (la versión con APIs que ya usás)
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  permission_handler: ^11.0.1

  # Utilidades
  android_alarm_manager_plus: ^5.0.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png